Reverse most of SwingMovement
odyssey-modding/odyssey pull request #21
Opened 2023-09-03 13:05 UTC by polybiusproxy

Reversed every function except for `updateRotate`. Everything matches.

2023-09-03 14:54 UTC, MonsterDruide1 requested changes
Great job at picking up our styling! Just a few nits, I'd love to see you try to take on `updateRotate` as well though.

2023-09-03 14:54 UTC, MonsterDruide1 commented on lib/al/Library/Math/MathSpeedUtil.h
clang-format

2023-09-03 14:54 UTC, MonsterDruide1 commented on lib/al/Library/Movement/RailMovement.cpp
> +      field_28(0.0) {
Use header-defined default values instead of initializer list

2023-09-03 14:54 UTC, MonsterDruide1 commented on lib/al/Library/Movement/RailMovement.cpp
> +      field_28(0.0) {
see above (header defined)

2023-09-03 14:54 UTC, MonsterDruide1 commented on lib/al/Library/Movement/RailMovement.h
> +    s32 field_10;
Looks like some sort of counter

2023-09-03 14:54 UTC, MonsterDruide1 commented on lib/al/Library/Movement/RailMovement.cpp
> +#include <al/Library/Movement/RailMovement.h>
This file does not exist, and doesn't seem to be used in here.

2023-09-03 15:08 UTC, polybiusproxy commented
> Great job at picking up our styling!

Thanks!

> I'd love to see you try to take on `updateRotate` as well though.

I initially didn't reverse it as it was a long function. I'll take a look at it though.
I also don't quite understand that function. It's adding `angle` twice when calling `al::modf`? I assume it's actually `angle * 2`, but it doesn't make quite a lot of sense for the compiler to optimize it like that.

2026-01-10 17:08 UTC, MonsterDruide1 commented
Implemented by @Fuzzy2319 in https://github.com/MonsterDruide1/OdysseyDecomp/pull/290.

2026-01-10 17:08 UTC, closed without merging